spring.application.name=testhms

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

app.jwt.secret=wildwings_super_secret_key_change_in_production
app.jwt.expiration=86400000